### ISSUE TITLE
SVG Units

### ISSUE THREAD

**Issue by AeroSteveO** [mattudakis/ArduinoLEDClock#6]
what are the units in the SVG files, inkscape is reading them as 172mm across rather than 230mm across. The center to center distance on the LED template is also 12mm and not 16.5mm, so the LED strip size called out won't fit the cutouts. The dividers have the slots at 1.5mm which matches the called out material sizes, however the length of them too is for a much smaller layout than the 9"x9" one called out.

**Comment by mattudakis** [comment]
It apears that Inkscape has a known issues when importing SVGs with setting incorrect scales. 
This can be corrected as shown here: https://www.youtube.com/watch?v=9qiYQDcmmQc

Unfortunatly if you correct the scale issue in inscape and then resave the .svg the dimentions are then incorrect in other vector based softwares such as adobe illustrator

I will update the readme and add additional files specific for inkscape

The correct dimentions for the WordClock_LED_template and the WordClock_Front_text should be 230mm x 230mm 
It looks like the WordClock_deviders_1.5mm file has been edited incorrectly due to this issue, which I will rectify.

**Comment by AeroSteveO** [comment]
I saw the same problem in LightBurn and CATIA as well. The scaling issue was strangest with the dividers where the slots were the correct 1.5mm while the rest of the size matched the smaller clock size at 7" or about a 12mm LED spacing.

**Comment by mattudakis** [comment]
> 

Having researched into this a bit more, it seems this is actually an adobe illustrator issue rather than an Inkscape problem. 
adobe exports .svgs with a 96ppi whereas the standard for .svgs is 72ppi which is why you were having issues with LightBurn and CATIA as well. I will fix the files to make them fit to the standard 72ppi and upload the files again.

**Comment by mattudakis** [comment]
The following commit ( 36f0f84 ) should have fixed this issue. I'll update the readme as well to mention compatability issues with adobe illustrator.
